apiVersion: v1
kind: Service
metadata:
  name: service-registry
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 32761
  selector:
    app: service-registry
    project: bc128-minet