apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql-secret
    project: bc128-minet
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=       # Base64 encoded value of 'password'  echo -n "password" | base64
  # MYSQL_USER: cm9vdA==                   # Base64 encoded value of 'root'
  # MYSQL_PASSWORD: Qm9vdGNhbXBAMTI4       # Base64 encoded value of 'Bootcamp@128'
