apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
spec:
  type: NodePort
  selector:
    app: database-sts
    project: bc128-minet
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32000  # You can specify a port number between 30000-32767
