server:
  port: 9094

spring:
  datasource:
    url: jdbc:mysql://18.217.159.117:3306/minet_bc_128_wallet?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    name: WALLET-SERVICE

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: init
    baseline-version: 1
    locations: classpath:db/migration
    validate-on-migrate: false
    mixed: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://3.144.212.170:8761/eureka/
      instanceInfoReplicationIntervalSeconds: 10
    instance:
      hostname: 3.144.212.170
