apiVersion: apps/v1
kind: Deployment
metadata:
   name: user-service
spec:
   replicas: 1
   selector:
      matchLabels:
         app: user-service
         project: bc128-minet
   template:
      metadata:
         labels:
            app: user-service
            project: bc128-minet
      spec:
         containers:
            - name: user-service
              image: ghcr.io/somnath-more/bc128-minet-be-user-service:latest
              imagePullPolicy: Always
              ports:
               - containerPort: 9091
              env:
                - name: EUREKA_INSTANCE_HOSTNAME
                  value: user-service

                - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                  value: http://discovery-service:8761/eureka/

                - name: SPRING_DATASOURCE_URL 
                  value: jdbc:mysql://18.188.123.194:32000/minet_bc_128_user?useSSL=false&serverTimezone=UTC

                - name: SPRING_DATASOURCE_PASSWORD
                  value: password

         imagePullSecrets:
           - name: ghcr-secret