apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  # annotations:
  #  cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - bc-128-fe.play-nooax-ai-with.me
  #     # secretName: letsencrypt-secret
  rules:
  - host: custom-nginx.codemaya.in
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: nginx-deployment   
            port:
              number: 80

              # ingress:8080  svc port 8080: containerPort: 80