server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://18.188.123.194:32000/minet_bc_128_crypto?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    name: CRYPTO-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      instanceInfoReplicationIntervalSeconds: 10
    instance:
      hostname: ${EUREKA_INSTANCE_HOSTNAME}
geckoUrl : https://api.coingecko.com/api/v3/coins/markets