name: bootcamp1128 backend deployment

on:
  push:
    branches:
      - deploy
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    strategy:
      matrix:
        service: [api-gateway,wallet-service,portfolio-service,crypto-service,service-registry,user-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and Push image to ghcr 
        env:
          SERVICE_NAME: ${{ matrix.service }}
        uses:  docker/build-push-action@v3
        with:
          push: true
          context: backend/${SERVICE_NAME}
          tags: |
             docker build -t ghcr.io/${{ github.actor }}/bc128-minet-be-${SERVICE_NAME}:v${{github.run_number}}
             docker tag ghcr.io/${{ github.actor}}/bc128-minet-be-${SERVICE_NAME}:latest

     
    #   - name: Configure AWS Credentials
    #     uses: aws-actions/configure-aws-credentials@v1
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: us-east-2

    #   - name: Adding EKS cluster and Build and Deploy the service
    #     env: 
    #       aws_region: us-east-2
    #       cluster_name: ${{ secrets.CLUSTER_NAME }}
    #       SERVICE_NAME: ${{ matrix.service }}
    #     run: |
    #       aws eks --region $aws_region update-kubeconfig --name $cluster_name
    #       cd backend/${SERVICE_NAME}

    #       mvn clean package -Dmaven.test.skip=true
    #       docker build -t ghcr.io/${{ env.GITHUB_USER }}/bc-109-backend-${SERVICE_NAME}:v${{ github.run_number }} .
    #       docker tag ghcr.io/${{ env.GITHUB_USER }}/bc-109-backend-${SERVICE_NAME}:v${{ github.run_number }} ghcr.io/${{ env.GITHUB_USER }}/bc-109-backend-${SERVICE_NAME}:latest
    #       docker push ghcr.io/${{ env.GITHUB_USER }}/bc-109-backend-${SERVICE_NAME}:v${{ github.run_number }}
    #       docker push ghcr.io/${{ env.GITHUB_USER }}/bc-109-backend-${SERVICE_NAME}:latest
    #       kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}-container=ghcr.io/${{ env.GITHUB_USER }}/bc-109-backend-${SERVICE_NAME}:v${{ github.run_number }}
    #   - name: remove kubeconfig file
    #     run: |
    #         ls ~/.kube
    #         rm -rf ~/.kube
