name: Backend deployment

on:
  push:
    branches:
      - deployment
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        service: [api-gateway, wallet-service, portfolio-service, crypto-service, service-registry, user-service]
    
    defaults:
      run:
        working-directory: backend/${{ matrix.service }}/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build with Maven
        run: |
          mvn clean package -Dmaven.test.skip=true

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v3
        with:
          push: true
          context: backend/${{ matrix.service }}/
          tags: |
             ghcr.io/${{ github.actor }}/bc128-minet-be-${{ matrix.service }}:v${{ github.run_number }}
             ghcr.io/${{ github.actor }}/bc128-minet-be-${{ matrix.service }}:latest
